/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gear_mostafa;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author taver
 */
public class ReliabilityForm extends javax.swing.JFrame implements Node{

    /**
     * Creates new form ReliabilityForm
     */
    public ReliabilityForm(HomePage1 aThis) {
        this.HomePage = aThis;
        initComponents();
    }
    HomePage1 HomePage;
     private Node parent;
     @Override
    public Node getParentNode() {
        return parent;
    }
    @Override
    public void setParentNode(Node node) {
        this.parent = node;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        koCalcButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        RfBox = new javax.swing.JComboBox<>();
        RfButton = new javax.swing.JButton();

        koCalcButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        koCalcButton.setText("Calculate");
        koCalcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koCalcButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Reliability Factor");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Reliability");

        RfBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RfBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.9999", "0.999", "0.99", "0.9", "0.5" }));
        RfBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RfBoxActionPerformed(evt);
            }
        });

        RfButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RfButton.setText("Calculate");
        RfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RfButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RfBox, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(RfButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RfBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(RfButton)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RfBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RfBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_RfBoxActionPerformed

    private void koCalcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koCalcButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_koCalcButtonActionPerformed

    private void RfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RfButtonActionPerformed
        // TODO add your handling code here:
        switch (RfBox.getSelectedIndex()) {
            case 0 -> HomePage.Rfvalue = 1.50;
            case 1 -> HomePage.Rfvalue =1.25;
            case 2 -> HomePage.Rfvalue =1;
            case 3 -> HomePage.Rfvalue = 0.85;
            case 4 -> HomePage.Rfvalue = 0.70;
            default -> {
            }
        }
      
        //System.out.println("KoValue" + HomePage.KoValue);
        JOptionPane.showMessageDialog(null," Reliability factor = " + HomePage.Rfvalue);
        HomePage.RfButton.setBorder(BorderFactory.createLineBorder(Color.GREEN,3));
        HomePage.RfButton.setOpaque(true);
        this.setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);

    }//GEN-LAST:event_RfButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> RfBox;
    private javax.swing.JButton RfButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton koCalcButton;
    // End of variables declaration//GEN-END:variables
}
